#####################################################
# AWS IOT CORE - rules, thing, policy, & certificates
#####################################################

# data "aws_iot_endpoint" "mqtt_endpoint" {
#   endpoint_type = "iot:Data-ATS"
# }
#
# # IoT TOPIC RULE - Routes incoming MQTT payloads to Timestream
# resource "aws_iot_topic_rule" "telemetry_ingestion" {
#   enabled     = true
#   name        = replace("${var.project_name}_${var.environment}_ingest_rule","-","_")
#   description = "Ingests MQTT telemetry message from devices into Timestream"
#   sql         = "SELECT *,clientid() as device_id FROM 'telemetry/+/data'"
#   sql_version = "2016-03-23"
#
#   # Timestream
#
#   tags = {
#     Environment = var.environment
#     ManagedBy = "Terraform"
#   }
# }
#
# # IoT POLICY - Least-privilege rules that is dynamic to the client's ThingName
# resource "aws_iot_policy" "device_policy" {
#   name   = "${var.project_name}-${var.environment}-device-policy"
#   policy = jsonencode({
#     Version = "2012-10-17"
#     Statement = [
#       {
#         Effect = "Allow"
#         Action = ["iot:Connect"]
#         Resource = ["arn:aws:iot:${var.aws_region}:*:client/$${iot:Connection.Thing.ThingName}"]
#       },
#       {
#         Effect = "Allow"
#         Action = ["iot:Publish"]
#         Resource = ["arn:aws:iot:${var.aws_region}:*:topic/telemetry/$${iot:Connection.Thing.ThingName}/data"]
#       },
#       {
#         Effect = "Allow"
#         Action = ["iot:Subscribe", "iot:Receive"]
#         Resource = ["arn:aws:iot:${var.aws_region}:*:topicfilter/telemetry/$${iot:Connection.Thing.ThingName}/control"]
#       },
#     ]
#   })
# }
#
# # IoT Thing - The logical device representation in AWS registry
# resource "aws_iot_thing" "simulator_device" {
#   name = "${var.project_name}-${var.environment}-sim-01"
#
#   attributes = {
#     device_type = "python_simulator"
#     environment = var.environment
#   }
# }
#
# # X.509 Device Certificate - Generated by AWS CA
# resource "aws_iot_certificate" "device_cert" {
#   active = true
# }
#
# # Attach Policy -> Certificate
# resource "aws_iot_policy_attachment" "cert_policy_attach" {
#   policy = aws_iot_policy.device_policy.name
#   target = aws_iot_certificate.device_cert.arn
# }
#
# # Attach Certificate -> Thing
# resource "aws_iot_thing_principal_attachment" "thing_cert_attach" {
#   principal = aws_iot_certificate.device_cert.arn
#   thing     = aws_iot_thing.simulator_device.name
# }
