#####################################################
# AWS IOT CORE - rules, thing, policy, & certificates
#####################################################

data "aws_iot_endpoint" "mqtt_endpoint" {
  endpoint_type = "iot:Data-ATS"
}

# IoT Topic Rule: Route incoming MQTT payloads to Lambda
resource "aws_iot_topic_rule" "telemetry_ingestion" {
  name        = replace("${var.project_name}_${var.environment}_ingest_rule", "-", "_")
  description = "Ingests MQTT telemetry messages and invokes Lambda to store in TimescaleDB"
  enabled     = true
  sql         = "SELECT *, clientid() as device_id FROM 'telemetry/+/data'"
  sql_version = "2016-03-23"

  lambda {
    function_arn = aws_lambda_function.iot_ingestor.arn
  }

  # Error Action: Fallback logging to CloudWatch if Lambda invocation fails
  error_action {
    cloudwatch_logs {
      log_group_name = "/aws/iot/rules/${var.project_name}_${var.environment}_errors"
      role_arn       = aws_iam_role.iot_cw_role.arn
    }
  }
  tags = {
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}


# Grant IoT Core service permission to invoke the Lambda function
resource "aws_lambda_permission" "allow_iot_to_lambda" {
  statement_id  = "AllowExecutionFromIoTCore"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.iot_ingestor.function_name
  principal     = "iot.amazonaws.com"
  source_arn    = aws_iot_topic_rule.telemetry_ingestion.arn
}

# IoT POLICY - Least-privilege rules that is dynamic to the client's ThingName
# added multi-sim support
# added Device Shadow ($aws/things) topics
resource "aws_iot_policy" "device_policy" {
  name = "${var.project_name}-${var.environment}-device-policy"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = ["iot:Connect"]
        # Allows any simulator prefixed with your project name (e.g. sim-01, sim-02)
        Resource = ["arn:aws:iot:${var.aws_region}:*:client/${var.project_name}-${var.environment}-sim-*"]
      },
      {
        Effect = "Allow"
        Action = ["iot:Publish"]
        Resource = [
          "arn:aws:iot:${var.aws_region}:*:topic/telemetry/${var.project_name}-${var.environment}-sim-*/data",
          "arn:aws:iot:${var.aws_region}:*:topic/$aws/things/${var.project_name}-${var.environment}-sim-*/shadow/*"
        ]
      },
      {
        Effect = "Allow"
        Action = ["iot:Subscribe"]
        # iot:Subscribe MUST use 'topicfilter/'
        Resource = [
          "arn:aws:iot:${var.aws_region}:*:topicfilter/telemetry/${var.project_name}-${var.environment}-sim-*/control",
          "arn:aws:iot:${var.aws_region}:*:topicfilter/$aws/things/${var.project_name}-${var.environment}-sim-*/shadow/*",
        ]
      },
      {
        Effect = "Allow"
        Action = ["iot:Receive"]
        # iot:Receive MUST use 'topic/'
        Resource = [
          "arn:aws:iot:${var.aws_region}:*:topic/telemetry/${var.project_name}-${var.environment}-sim-*/control",
          "arn:aws:iot:${var.aws_region}:*:topic/$aws/things/${var.project_name}-${var.environment}-sim-*/shadow/*",
        ]
      }
    ]
  })
}

# IoT Thing - The logical device representation in AWS registry
resource "aws_iot_thing" "simulator_device_01" {
  name = "${var.project_name}-${var.environment}-sim-01"

  attributes = {
    device_type = "python_simulator"
    environment = var.environment
  }
}

resource "aws_iot_thing" "simulator_device_02" {
  name = "${var.project_name}-${var.environment}-sim-02"

  attributes = {
    device_type = "python_simulator"
    environment = var.environment
  }
}

# X.509 Device Certificate - Generated by AWS CA
resource "aws_iot_certificate" "device_cert" {
  active = true
}

# Attach Policy -> Certificate
resource "aws_iot_policy_attachment" "cert_policy_attach" {
  policy = aws_iot_policy.device_policy.name
  target = aws_iot_certificate.device_cert.arn
}

# Attach Certificate -> ThingS
resource "aws_iot_thing_principal_attachment" "thing_cert_attach_01" {
  principal = aws_iot_certificate.device_cert.arn
  thing     = aws_iot_thing.simulator_device_01.name

  # prevent error race conditions
  depends_on = [
    aws_iot_thing.simulator_device_01,
    aws_iot_certificate.device_cert
  ]
}

resource "aws_iot_thing_principal_attachment" "thing_cert_attach_02" {
  principal = aws_iot_certificate.device_cert.arn
  thing     = aws_iot_thing.simulator_device_02.name

  # prevent error race conditions
  depends_on = [
    aws_iot_thing.simulator_device_02,
    aws_iot_certificate.device_cert
  ]
}

# IAM Role for IoT CloudWatch Error Logging
resource "aws_iam_role" "iot_cw_role" {
  name = "${var.project_name}-${var.environment}-iot-cw-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action    = "sts:AssumeRole"
      Effect    = "Allow"
      Principal = { Service = "iot.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "iot_cw_attach" {
  role       = aws_iam_role.iot_cw_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSIoTLogging"
}
